cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules


before_install:
- npm i -g yarn

install:
- yarn

language: node_js

matrix:
  include:
    - node_js: "4"
      script: "npm run feature-test"
    - node_js: "7"
      script: "npm run feature-test"

node_js: "6"

notifications:
  email: false

sudo: false
