cache:
  directories:
    - $HOME/node_modules

language: node_js

matrix:
  include:
    - node_js: "4"
      script: "npm run feature-test"
    - node_js: "7"
      script: "npm run feature-test"

node_js: "6"

notifications:
  email: false

sudo: false
