before_install:
- npm i -g yarn

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

deploy:
  api_key: "$NPM_AUTH_TOKEN"
  email: "hello@originate.com"
  on:
    node: '6'
    tags: true
  provider: npm
  skip_cleanup: true

install:
- yarn

language: node_js

matrix:
  include:
    - node_js: "4"
      script: "npm run feature-test"
    - node_js: "7"
      script: "npm run feature-test"

node_js: "6"

notifications:
  email: false

sudo: false
