#!/usr/bin/env node
// Generated by CoffeeScript 1.6.2
var Mycha, mycha, options;

Mycha = require(__dirname + '/mycha');

options = {
  mochaArgs: process.argv.slice(3)
};

mycha = new Mycha(process.cwd(), options);

mycha.run();
